# -*- coding: utf-8 -*-
"""IA_Práctica11-ClasificaciónRLog(CáncerMama).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l4reGgP2raPDJsgAEJ85f6HMMpjtqhrC

# **Práctica 11: Clasificación (Cáncer de mama)**

Nombre:

No. Cuenta:

Email:

### **Caso de estudio**

Estudios clínicos a partir de imágenes digitalizadas de pacientes con cáncer de mama de Wisconsin (WDBC, Wisconsin Diagnostic Breast Cancer).

**Objetivo.** Clasificar registros clínicos de tumores malignos y benignos de cancer de mama a partir de imágenes digitalizadas.

**Fuente de datos:**

https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)

#### **1) Importar las bibliotecas necesarias y los datos**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd               # Para la manipulación y análisis de datos
import numpy as np                # Para crear vectores y matrices n dimensionales
import matplotlib.pyplot as plt   # Para la generación de gráficas a partir de los datos
import seaborn as sns             # Para la visualización de datos basado en matplotlib
# %matplotlib inline

BCancer = pd.read_csv('Datos/WDBCOriginal.csv')
BCancer

print(BCancer.groupby('Diagnosis').size())

"""#### **2) Selección de características**

Se utiliza una matriz de correlaciones con el propósito de seleccionar variables significativas.
"""

sns.pairplot(BCancer, hue='Diagnosis')
plt.show()

#plt.plot(BCancer['Radius'], BCancer['Perimeter'], 'b+')
sns.scatterplot(x='Radius', y ='Perimeter', data=BCancer, hue='Diagnosis')
plt.title('Gráfico de dispersión')
plt.xlabel('Radius')
plt.ylabel('Perimeter')
plt.show()

CorrBCancer = BCancer.corr(method='pearson')
CorrBCancer

plt.figure(figsize=(14,7))
MatrizInf = np.triu(BCancer.corr())
sns.heatmap(BCancer.corr(), cmap='RdBu_r', annot=True, mask=MatrizInf)
plt.show()

"""**Varibles seleccionadas:**

1) Textura [Posición 3]

2) Area [Posición 5]

3) Smoothness [Posición 6]

4) Compactness [Posición 7]

5) Symmetry [Posición 10]

6) FractalDimension [Posición 11]

#### **3) Definición de variables predictoras y variable clase**
"""

BCancer = BCancer.replace({'M': 0, 'B': 1})
BCancer

print(BCancer.groupby('Diagnosis').size())

#Variables predictoras
X = np.array(BCancer[['Texture', 
                      'Area', 
                      'Smoothness', 
                      'Compactness', 
                      'Symmetry', 
                      'FractalDimension']])
#X = BCancer.iloc[:, [3, 5, 6, 7, 10, 11]].values  #iloc para seleccionar filas y columnas según su posición
pd.DataFrame(X)

#Variable clase
Y = np.array(BCancer[['Diagnosis']])
pd.DataFrame(Y)

plt.figure(figsize=(10, 7))
plt.scatter(X[:,0], X[:,1], c = BCancer.Diagnosis)
plt.grid()
plt.xlabel('Texture')
plt.ylabel('Area')
plt.show()

"""#### **4) Aplicación del algoritmo**

Regresión logística


"""

#Se importan las bibliotecas necesarias para generar el modelo de regresión logística
from sklearn import model_selection
from sklearn import linear_model
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, 
                                                                test_size = 0.2, 
                                                                random_state = 1234,
                                                                shuffle = True)

pd.DataFrame(X_train)

print(len(X_train))
print(len(X_validation))

#Se entrena el modelo a partir de los datos de entrada
ClasificacionRL = linear_model.LogisticRegression()
ClasificacionRL.fit(X_train, Y_train)

"""Se generan las probabilidades"""

#Predicciones probabilísticas de los datos de prueba
Probabilidad = ClasificacionRL.predict_proba(X_validation)
pd.DataFrame(Probabilidad).round(4)

#Clasificación final 
Y_ClasificacionRL = ClasificacionRL.predict(X_validation)
print(Y_ClasificacionRL)

#Se calcula la exactitud promedio de la validación
accuracy_score(Y_validation, Y_ClasificacionRL)

"""#### **5) Validación del modelo**

"""

#Matriz de clasificación
ModeloClasificacion = ClasificacionRL.predict(X_validation)
Matriz_Clasificacion = pd.crosstab(Y_validation.ravel(), 
                                   ModeloClasificacion, 
                                   rownames=['Reales'], 
                                   colnames=['Clasificación']) 
Matriz_Clasificacion

#Reporte de la clasificación
print("Exactitud:", accuracy_score(Y_validation, Y_ClasificacionRL))
print(classification_report(Y_validation, Y_ClasificacionRL))

from sklearn.metrics import RocCurveDisplay
CurvaROC = RocCurveDisplay.from_estimator(ClasificacionRL, X_validation, Y_validation, name="Cáncer de mama")
plt.show()

"""#### **6) Ecuación del modelo de clasificación**"""

#Ecuación del modelo
print("Intercept:", ClasificacionRL.intercept_)
print('Coeficientes: \n', ClasificacionRL.coef_)

"""
Prob = 1/1+𝑒^−(𝑎+𝑏𝑋))

𝑎+𝑏𝑋 = 12.025 – 0.195Texture – 0.011Area – 0.707Smoothness – 2.592Compactness – 1.025Symmetry – 0.257FractalDimension
"""

#Paciente P-842302 (1) -Tumor Maligno-
PacienteID1 = pd.DataFrame({'Texture': [12.38], 
                            'Area': [1500.0], 
                            'Smoothness': [0.11840], 
                            'Compactness': [0.27760], 
                            'Symmetry': [0.2419], 
                            'FractalDimension': [0.07871]})
ClasificacionRL.predict(PacienteID1)

#Paciente P-92751 (569) -Tumor Benigno-
PacienteID2 = pd.DataFrame({'Texture': [24.54], 
                            'Area': [181.0], 
                            'Smoothness': [0.05263], 
                            'Compactness': [0.04362], 
                            'Symmetry': [0.1587], 
                            'FractalDimension': [0.05884]})
ClasificacionRL.predict(PacienteID2)

